# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Manawadu M.S-Cobsccomp171p008' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Manawadu M.S-Cobsccomp171p008

  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'SwiftyJSON'
  pod 'Firebase/Storage'  
  pod 'Alamofire', '~>4.4'
  pod 'Kingfisher', '~> 4.0' 
  pod 'GoogleSignIn'
end
